### ISSUE TITLE
It's not working at all

### ISSUE THREAD

**Issue by ferox** [x0uid/SpotifyAdBlock#12]
Can't play, even listen by web browser.

OS.: Fedora distro (Linux).

![cant-play-listen-spotify](https://user-images.githubusercontent.com/7634766/80211659-76dac600-860c-11ea-9850-65a8d5cf699e.png)

**Comment by x0uid** [comment]
Yeah, for web browser isn't possible entire to block advertising without breaking web client. 

If i was u try using Spotify client via snap https://snapcraft.io/spotify. Works perfectly, meanwhile will look deeper into web client issues to get working again.

**Comment by umlautfever** [comment]
I can't confirm if this works when you also have the block list in the hosts file, but Ublock-Origin (the ad blocking extension) works to block any ads on the browser version
(it looks like you have a browser that would accept the extension?)

**Comment by Murplugg** [comment]
Works on desktop. Thanks for this.

**Comment by Murplugg** [comment]
Wait, actually got an ad today on Win OS. Can you confirm it works with the latest version?
