### ISSUE TITLE
List upsets facebook

### ISSUE THREAD

**Issue by jrbray1** [x0uid/SpotifyAdBlock#13]
Using the list unchaged on Linux Mint, Facebook switches to a text-only mode with no content on the web page

**Comment by x0uid** [comment]
Good day sir. Not sure if its my list, i just made a test Facebook account.... And here is result.
![Screenshot_2020-05-11 Facebook](https://user-images.githubusercontent.com/52933635/81584228-c6621580-93b2-11ea-9553-3a99104427fe.png)

**Comment by jrbray1** [comment]
If I have your lines in my /etc/hosts, I have the problem, it shows as a text only mode of Facebook (like the fallback options for websites detecting low bandwidth) with no content from my friends (I block the ads within the browser). As soon as I remove them it goes away.,

**Comment by quin1313** [comment]
I am also in the UK, and it's working fine for me, no problems at all.

**Comment by x0uid** [comment]
> 
> 
> If I have your lines in my /etc/hosts, I have the problem, it shows as a text only mode of Facebook (like the fallback options for websites detecting low bandwidth) with no content from my friends (I block the ads within the browser). As soon as I remove them it goes away, I am in the UK, if that makes a difference as to what servers are being used.
> 
> I tried a binary chop on the hosts file, but the caching in Linux defeated me

Are you using Pi-Hole? Or host file only?

**Comment by jrbray1** [comment]
Just hosts file

**Comment by couraudt** [comment]
I have the same issue and after debugging using dnsmasq it appear that the issue is coming from blocked domain `scontent.xx.fbcdn.net`

**Comment by x0uid** [comment]
> 
> 
> I have the same issue and after debugging using dnsmasq it appear that the issue is coming from blocked domain `scontent.xx.fbcdn.net`

Thanks for reporting the issue, i indeed tested and you are right. It slightly blocking some content images, that why removed the dns from the list.

**Comment by couraudt** [comment]
Thank for maintaining this repo!

**Comment by x0uid** [comment]
You're welcome!
