### ISSUE TITLE
Audio ads are still present

### ISSUE THREAD

**Issue by GameSpeck** [x0uid/SpotifyAdBlock#19]
Hi, I am on Ubuntu 20.04 LTS and I added all the hosts in the hosts file but there are still audio ads. Using Spotify v1.1.26.501.gbe11e53b-15

**Comment by x0uid** [comment]
30 second ads cant be removed its streamed via Spotify's main music DNS, that's why you cant block it. But :.

A: it doesn't collect any information. 
B: It's every 10/15 minutes.

**Comment by GameSpeck** [comment]
Oh okay, actually when I was on Windows there was an old Spotify app with some hosts provided by a friend, it didn't had any audio ads either so that's why I asked if it's possible to remove those audio ads. But anyways now that I know it cannot be removed, I will close this issue.
