### ISSUE TITLE
Blocks ads for sure, but won't skip it

### ISSUE THREAD

**Issue by yotsashi** [x0uid/SpotifyAdBlock#2]
As I've used host files before, I know I've used them properly, but spotify still tries to play ads. When this happens, the program goes silent and on where the album cover is, I see the blank disc symbol with "Learn More" next to it. clicking pause or play makes no difference other than on the button itself. When I try to click on another song, the banner pops on top saying "The selected song will play after the ads"

But it certainly blocks the playable ads

Edit: I restarted my computer to see if it would help fix the problem, and it does but not in a way I'd prefer. Because ads play

**Comment by yotsashi** [comment]
I restarted my computer to see if it would help fix the problem, and it _does_ but not in a way I'd prefer. Because ads play

**Comment by x0uid** [comment]
Hi,

Also info on what ads are being played?!

**Comment by yotsashi** [comment]
they are the typical Spotify premium ads, pima institute, state farm, charmin, and army recruitment are a few that I've caught

By the way, thank you so much for your work on this! after restarting my computer, I've noticed fewer ads. It'd usually be about 4 ads each time ads played, but now it's only one or two each time

**Comment by x0uid** [comment]
Thanks for information, will try to intercept those...

Also you are welcome.
