### ISSUE TITLE
Also seems to block w3schools

### ISSUE THREAD

**Issue by QazCetelic** [x0uid/SpotifyAdBlock#30]
I'm unable to visit w3schools when using this.

**Comment by ochen1** [comment]
Hi there!

Can you press Ctrl. Shift I when visiting w3schools and go to the network tab.

Do you see anything that's not a 200 (usually failed would cause it to appear in red text) inside there?

Can you attatch a screenshot?

**Comment by QazCetelic** [comment]
I'm unsure what to look for, but here's a screenshot.
![image](https://user-images.githubusercontent.com/51381523/101678343-1cd52680-3a5e-11eb-9bd4-4bed25639fb4.png)

**Comment by HoukasaurusRex** [comment]
I can visit this page fine on my system. Is the whole site broken or just this page? Could you also send what the status column says on your network tab? It appears to be cut off a bit.

**Comment by QazCetelic** [comment]
The entire site is unreachable. 
![image](https://user-images.githubusercontent.com/51381523/102541756-158ec800-40b1-11eb-938b-6ab8d31985f6.png)
