### ISSUE TITLE
Song doesn't plays

### ISSUE THREAD

**Issue by QSoto** [x0uid/SpotifyAdBlock#4]
I added list, select a song, but it doesn't start playing. I removed the list and music played as desired. Tried purging the list, removing any of "do not block this" coincidence or subdomain but it didn't work. Any sugestion?

**Comment by SealedJoy** [comment]
No hard evidence but from experience blocking ads via hosts alerts spotify to the fact all songs are playing but zero ads are. Solution could be to make spotify think the ad is playing as expected (by just muting the system volume)

**Comment by x0uid** [comment]
Fixed.
