### ISSUE TITLE
Spotify skipping musics

### ISSUE THREAD

**Issue by Jopherr** [x0uid/SpotifyAdBlock#5]
Recently, my Spotify started skipping songs randomly. I think it's something with the addresses in the hosts file, because when I remove them, my Spotify works normally.

**Comment by x0uid** [comment]
Please update your hosts file.

**Comment by monojp** [comment]
@x0uid I'm experiencing the same on https://open.spotify.com
Looks to be related to the blocking of `audio-ak-spotify-com.akamaized.net`, this seems to be the domain where the audio packets are loaded from?
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/5738896/76237654-e8161380-622e-11ea-9fa1-21ac372d1c15.png">
