### ISSUE TITLE
Non-GitHub mirror?

### ISSUE THREAD

**Issue by JayBrown** [x0uid/SpotifyAdBlock#8]
I'm using **[GasMask](https://github.com/2ndalpha/gasmask)** to create a combined hosts file from local and external sources, with regular automated updates for external sources. However, there's a **[bug in GasMask](https://github.com/2ndalpha/gasmask/issues/90)** in that it won't accept hosts files hosted on GitHub due to allegedly "bad" content. However, the same hosts files on a non-GitHub mirror work just fine. So my question is if it's possible to create a non-GitHub mirror. Or would that be too much of a hassle with all the updates?

**Comment by x0uid** [comment]
That's actually good idea, here's a mirror: [](https://blogpirate.net/SpotifyAdBlock/)
