### ISSUE TITLE
cs196.wac.edgecastcdn.net results in Twitter images being blocked

### ISSUE THREAD

**Issue by WaLLy3K** [x0uid/SpotifyAdBlock#9]
Pi-hole will state that `pbs.twimg.com` is being blocked when browsing Twitter (Specifically, I was browsing Tweetdeck), but this is due to it being a CNAME to `cs196.wac.edgecastcdn.net` which is blocked by this list.

I also notice the same is happening with `cs45.wac.edgecastcdn.net` and `ton.twimg.com`.

**Comment by x0uid** [comment]
Entrie's removed. Thanks for reporting.
